import React, { useEffect, useRef } from 'react'
import isEqual from 'react-fast-compare'
import { useCSSVariable } from '../../hooks/useCSSVariable'

// styles
import styles from './CodeHighlighter.module.scss'
import classNames from 'classnames'

// # --------------------------------------------------------------------------------
//
// prism import
//
// # --------------------------------------------------------------------------------

import Prism from 'prismjs'

//styles
import './prism-one-common.scss'

// line numbers
// @see https://prismjs.com/plugins/line-numbers/
import 'prismjs/plugins/line-numbers/prism-line-numbers.css'
import 'prismjs/plugins/line-numbers/prism-line-numbers.js'

// line highlight
// @see https://prismjs.com/plugins/line-highlight/
import 'prismjs/plugins/line-highlight/prism-line-highlight.css'
import 'prismjs/plugins/line-highlight/prism-line-highlight.js'

// language autoloader
import 'prismjs/plugins/autoloader/prism-autoloader.js'

// previewers @see https://prismjs.com/plugins/previewers/
import 'prismjs/plugins/previewers/prism-previewers.css'
import 'prismjs/plugins/previewers/prism-previewers.js'

// diff-highlight
import 'prismjs/plugins/diff-highlight/prism-diff-highlight.css'
import 'prismjs/plugins/diff-highlight/prism-diff-highlight.js'

// treeview
import 'prismjs/plugins/treeview/prism-treeview.css'
import 'prismjs/plugins/treeview/prism-treeview.js'

// commandline
import 'prismjs/plugins/command-line/prism-command-line.css'
import 'prismjs/plugins/command-line/prism-command-line.js'
import { useDeepCompareEffect } from 'react-use'

// # --------------------------------------------------------------------------------
//
// themes
//
// # --------------------------------------------------------------------------------

const ATOM_ONE_LIGHT = {
  '--mono-1': 'hsl(230, 8%, 24%)',
  '--mono-2': 'hsl(230, 6%, 44%)',
  '--mono-3': 'hsl(230, 4%, 64%)',
  '--hue-1': 'hsl(198, 99%, 37%)',
  '--hue-2': 'hsl(221, 60%, 46%)',
  '--hue-3': 'hsl(301, 63%, 40%)',
  '--hue-4': 'hsl(119, 34%, 47%)',
  '--hue-5': 'hsl(5, 74%, 59%)',
  '--hue-5-2': 'hsl(344, 84%, 43%)',
  '--hue-6': 'hsl(35, 99%, 36%)',
  '--hue-6-2': 'hsl(35, 99%, 40%)',
  '--syntax-fg': 'var(--mono-1)',
  '--syntax-bg': 'hsl(230, 1%, 98%)',
  '--syntax-gutter': 'hsl(230, 1%, 62%)',
  '--syntax-guide': 'hsla(230, 8%, 24%, 0.2)',
  '--syntax-accent': 'hsl(230, 100%, 66%)',
  '--syntax-selection-color': 'hsl(230, 1%, 90%)',
  '--syntax-gutter-background-color-selected': 'var(--syntax-selection-color)',
  '--syntax-cursor-line': 'hsla(230, 8%, 24%, 0.05)'
}

const ATOM_ONE_DARK = {
  '--mono-1': 'hsl(220, 14%, 71%)',
  '--mono-2': 'hsl(220, 9%, 55%)',
  '--mono-3': 'hsl(220, 10%, 40%)',
  '--hue-1': 'hsl(187, 47%, 55%)',
  '--hue-2': 'hsl(207, 82%, 66%)',
  '--hue-3': 'hsl(286, 60%, 67%)',
  '--hue-4': 'hsl(95, 38%, 62%)',
  '--hue-5': 'hsl(355, 65%, 65%)',
  '--hue-5-2': 'hsl(5, 48%, 51%)',
  '--hue-6': 'hsl(29, 54%, 61%)',
  '--hue-6-2': 'hsl(39, 67%, 69%)',
  '--syntax-fg': 'var(--mono-1)',
  '--syntax-bg': 'hsl(220, 13%, 18%)',
  '--syntax-gutter': 'hsl(220, 14%, 45%)',
  '--syntax-guide': 'hsla(220, 14%, 71%, 0.15)',
  '--syntax-accent': 'hsl(220, 100%, 66%)',
  '--syntax-selection-color': 'hsl(220, 13%, 28%)',
  '--syntax-gutter-background-color-selected': 'hsl(220, 13%, 26%)',
  '--syntax-cursor-line': 'hsla(220, 100%, 80%, 0.04)'
}

// # --------------------------------------------------------------------------------
//
// utils
//
// # --------------------------------------------------------------------------------

function generatePrismDiff(oldCode: string, newCode: string): string {
  const oldLines = oldCode.split('\n')
  const newLines = newCode.split('\n')
  const maxLength = Math.max(oldLines.length, newLines.length)

  let diffResult = ''

  for (let i = 0; i < maxLength; i++) {
    const oldLine = oldLines[i] || ''
    const newLine = newLines[i] || ''

    if (oldLine === newLine) {
      diffResult += ` ${oldLine}\n`
    } else {
      if (oldLine) {
        diffResult += `-${oldLine}\n`
      }
      if (newLine) {
        diffResult += `+${newLine}\n`
      }
    }
  }

  return diffResult.trim()
}

// # --------------------------------------------------------------------------------
//
// props
//
// # --------------------------------------------------------------------------------

export interface CodeHighlighterProps {
  style?: React.CSSProperties
  preStyle?: React.CSSProperties
  codeStyle?: React.CSSProperties
  className?: string
  /**
   * Whether or not to use the dark theme
   */
  isDark?: boolean

  /**
   * Programming language. Affects syntax highlighting.
   *
   * ## Special Languages
   *
   * - `treeview`: Generates a file tree view. Specifically targets output generated by the `tree -F` command.
   * - `diff`: Highlights code differences. Automatically generates and highlights a diff when `code` and `oldCode` values are provided.
   */
  language?: string

  /**
   * The content of the code
   */
  code: string

  /**
   * Used for creating a diff. If this prop is provided, the language will be
   * forced to `'diff'`.
   */
  oldCode?: string

  /**
   * Transition duration (in milliseconds) for theme changes
   */
  transitionDuration?: number

  /**
   * If `true`, numbers will be displayed on the left side of the code.
   */
  showLineNumber?: boolean

  /**
   * @see https://prismjs.com/plugins/line-highlight/
   *
   * Highlights specific lines. e.g., `['5', '14-17']`
   */
  highlightLines?: (string | number)[]

  /**
   * @see https://prismjs.com/plugins/command-line/
   */
  commandLine?: {
    /**
     * Username displayed in the prompt. Default value is `user`.
     */
    user?: string
    /**
     * Hostname displayed in the prompt. Default value is `localhost`.
     */
    host?: string
    /**
     * Lines marked as standard output. Only the left side of standard input lines will display the prompt.
     * e.g., `['2', '4-8']`
     */
    output?: (string | number)[]
    /**
     * Fully customizable prompt. e.g., `$`
     */
    prompt?: string
    continuationPrompt?: string
    continuationStr?: string
    filterOutput?: string
    filterContinuation?: string
  }
}

// # --------------------------------------------------------------------------------
//
// component
//
// # --------------------------------------------------------------------------------

const CodeHighlighterComponent = (props: CodeHighlighterProps) => {
  const {
    style,
    preStyle,
    codeStyle,
    className,
    isDark = typeof window !== 'undefined'
      ? window.matchMedia('(prefers-color-scheme: dark)').matches
      : false,
    code,
    oldCode,
    language = oldCode != null ? 'diff' : 'txt',
    transitionDuration = 400,
    showLineNumber = false,
    highlightLines = [],
    commandLine
  } = props

  // # --------------------------------------------------------------------------------
  //
  // render
  //
  // # --------------------------------------------------------------------------------

  const codeRef = useRef(null)

  const highlight = () => {
    Prism.plugins.autoloader.languages_path =
      'https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/'
    if (codeRef.current) {
      Prism.highlightElement(codeRef.current)
    }
  }

  useEffect(() => {
    highlight()
  }, [code, oldCode, language, showLineNumber])

  useDeepCompareEffect(() => {
    highlight()
  }, [highlightLines, commandLine])

  // # --------------------------------------------------------------------------------
  //
  // CSS Variables
  //
  // # --------------------------------------------------------------------------------

  const { ref: cssRef } = useCSSVariable({
    '--react-transition-duration': transitionDuration + 'ms',
    ...(isDark ? ATOM_ONE_DARK : ATOM_ONE_LIGHT)
  })

  // # --------------------------------------------------------------------------------
  //
  // render
  //
  // # --------------------------------------------------------------------------------

  return (
    <div
      style={{ ...style }}
      ref={cssRef}
      className={classNames(
        styles['code-highlighter'],
        'relmethis-codeblock-container-common',
        className
      )}
    >
      <pre
        style={{
          ...preStyle,
          paddingLeft:
            highlightLines.length > 0 && !showLineNumber ? '2.5rem' : undefined
        }}
        className={classNames(styles['code-highlighter__pre'], {
          ['line-numbers']: commandLine != null ? false : showLineNumber,
          ['command-line']: commandLine != null
        })}
        data-line={highlightLines.join(', ')}
        data-user={commandLine?.user}
        data-host={commandLine?.host}
        data-output={commandLine?.output?.join(', ')}
        data-prompt={commandLine?.prompt}
        data-continuation-prompt={commandLine?.continuationPrompt}
        data-continuation-str={commandLine?.continuationStr}
        data-filter-output={commandLine?.filterOutput}
        data-filter-continuation={commandLine?.filterContinuation}
      >
        <code
          ref={codeRef}
          className={classNames(
            `language-${language}`,
            styles['code-highlighter__code']
          )}
          style={codeStyle}
        >
          {oldCode != null
            ? generatePrismDiff(oldCode.trim(), code.trim())
            : code.trim()}
        </code>
      </pre>
    </div>
  )
}

// # --------------------------------------------------------------------------------
//
// memoize
//
// # --------------------------------------------------------------------------------

export const CodeHighlighter = React.memo(CodeHighlighterComponent, isEqual)
